### PR TITLE
Casts for std::unique_ptr and std::shared_ptr

### PR DESCRIPTION
**Pull request by koraa**
I am currently trying to implement the smart_ptr casts for both std::shared_ptr and std::unique_ptr.

It is not finished yet: this PR serves to track the progress and to discuss the code structure and design of those features, since I am pretty sure there are some improvements needed there :)

I started a mailing list thread about this a while ago: http://lists.boost.org/Archives/boost/2015/10/225912.php

Most of the core functionality is implemented, that includes all the casts for std::shared_ptr and std::unique_ptr and tests.

Currently I am considering the following changes before merge:
* Tests for reinterpret_cast (it was untested before)
* Tests for intrusive_ptr
* Moving casts for scoped_ptr
* Refactoring the tests; at the moment I am using std::function to generate pointers for the moving casts. I am not sure whether that's OK. Besides, there is a lot of code duplication between the moving cast tests and the old tests, that could be removed.
* Document when the approach seams stable

### CODE REVIEW

**Comment by koraa** [comment]
Since this came up in the mailing list, here is a motivating example: http://melpon.org/wandbox/permlink/R3QWA7MaxZ5o1ocG

**Comment by Flast** [comment]
How do you think about allowing unsafe cast, which I replied you http://lists.boost.org/Archives/boost/2015/10/225991.php.

> Since this came up in the mailing list, here is a motivating example: http://melpon.org/wandbox/permlink/R3QWA7MaxZ5o1ocG

It also has same problem, like this http://melpon.org/wandbox/permlink/zUICUvPcQFoHmT5I.

**Comment by koraa** [comment]
Hi @Flast ,
I looked at your code before writing this PR and I thought the problem was mainly associated with not making the casts nothrow. Sorry I missed the bit about the destructors :)

In the modified version of my example, I see that the destructor of the non_trivial_dtor_listener is not being called. That's because the base class was declared without a virtual constructor. afaik you run into the same problem when using any other pointer type – destructor just need to be virtual for runtime polymorphism.

In your original example. I see the same case as above and I also see, that you can not move the deleter of a unique pointer. As I understand it, being able to cast the deleter would be nice feature, but it isn't a problem for an implementation that simply doesn't provide that feature – i.e. only works with std::default_delete on parameter and return value.

**Comment by koraa** [comment]
@Flast Maybe we can actually add a static_assert to warn about that case (downcasting to something with a non virtual destructor)

**Comment by Flast** [comment]
> Maybe we can actually add a static_assert to warn about that case (downcasting to something with a non virtual destructor)

Agreed. [`boost::has_virtual_destructor`](http://www.boost.org/doc/libs/1_60_0/libs/type_traits/doc/html/boost_typetraits/reference/has_virtual_destructor.html) will help.

**Comment by koraa** [comment]
@Flast There is also a std implementation, http://www.cplusplus.com/reference/type_traits/has_virtual_destructor/ . I though it would be better to use this, since it would pull less requirements. Is this correct?

**Comment by Flast** [comment]
> I though it would be better to use this, since it would pull less requirements. Is this correct?

IMO, Boost.TypeTraits is better than std's: you should check `BOOST_NO_CXX11_HDR_TYPE_TRAITS` to use `<type_traits>`.

**Comment by pdimov** [comment]
I created a feature branch for this - feature/unique_ptr_casts. Still needs a few more tests, will add them later.

**Comment by koraa** [comment]
Thank you very much! I didn't really know which test cases to write :)

**Pull request merged**
