### PR TITLE
Merge develop

### PR DESCRIPTION
**Pull request by glenfe**
Pull request to trigger all compilers tests

### CODE REVIEW

**Comment by pdimov** [comment]
Every push to develop is automatically tested, so there's no need to trigger that with a PR, although it doesn't hurt. You can see the results in

https://github.com/boostorg/smart_ptr/commits/develop

**Comment by pdimov** [comment]
Although on second thought this tests master, not develop, so it's not the same.

**Comment by glenfe** [comment]
That's interesting. I created this pull request via the github.com user interface which, I think, should be a non-fast-forward merge according to [this](https://help.github.com/articles/merging-a-pull-request/).

**Comment by pdimov** [comment]
That's however about merging the pull request.

Things are of course a bit tricky when the PR consists of a merge.

Anyway, Travis did run, so you could just test locally on however many MSVC versions you have and then push.

**Pull request merged**
